---
fixtures:
  repositories:
    vim:
      ref: "v2.4.0"
      repo: "https://github.com/saz/puppet-vim"
    vcsrepo:
      ref: "1.5.0"
      repo: "https://github.com/puppetlabs/puppetlabs-vcsrepo"
    archive:
      ref: "v1.3.0"
      repo: "https://github.com/voxpupuli/puppet-archive"
    stdlib:
      ref: "4.16.0"
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
  symlinks:
    vision_editors: '#{source_dir}'
