---
fixtures:
  repositories:
    stdlib:
      ref: "v6.0.0"
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    vcsrepo:
      ref: "v3.0.0"
      repo: "https://github.com/puppetlabs/puppetlabs-vcsrepo"
    archive:
      ref: "v4.2.0"
      repo: "https://github.com/voxpupuli/puppet-archive"
  symlinks:
    vision_editors: '#{source_dir}'
