---
fixtures:
  repositories:
    stdlib:
      ref: "v6.2.0"
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    archive:
      ref: "v4.4.0"
      repo: "https://github.com/voxpupuli/puppet-archive"
  symlinks:
    vision_editors: '#{source_dir}'
