---
fixtures:
  repositories:
    stdlib:
      ref: "4.24.0"
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    vcsrepo:
      ref: "2.2.0"
      repo: "https://github.com/puppetlabs/puppetlabs-vcsrepo"
    archive:
      ref: "v2.3.0"
      repo: "https://github.com/voxpupuli/puppet-archive"

  symlinks:
    vision_editors: '#{source_dir}'
